# Generated by Django 6.0.2 on 2026-02-16 15:19

import autoslug.fields
import dms.models.foundation_model
import dms.models.people_model
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.CharField(choices=[('qaida', 'نورانی قاعدہ'), ('nazra', 'ناظرہ قرآن'), ('hifz', 'حفظ قرآن'), ('deenyat', 'دینیات'), ('other', 'دیگر'), ('dars', 'درس نظامی'), ('aalim', 'عالم کورس'), ('ifta', 'افتاء'), ('tafseer', 'تفسیر'), ('arabic_adab', 'عربی ادب'), ('islamyat', 'اسلامیات')], max_length=50, verbose_name='زمرہ'),
        ),
        migrations.AlterField(
            model_name='historicalcourse',
            name='category',
            field=models.CharField(choices=[('qaida', 'نورانی قاعدہ'), ('nazra', 'ناظرہ قرآن'), ('hifz', 'حفظ قرآن'), ('deenyat', 'دینیات'), ('other', 'دیگر'), ('dars', 'درس نظامی'), ('aalim', 'عالم کورس'), ('ifta', 'افتاء'), ('tafseer', 'تفسیر'), ('arabic_adab', 'عربی ادب'), ('islamyat', 'اسلامیات')], max_length=50, verbose_name='زمرہ'),
        ),
        migrations.AlterField(
            model_name='historicalinstitution',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, editable=True, populate_from=dms.models.foundation_model.get_institution_slug_source, slugify=dms.models.foundation_model.unicode_slugify),
        ),
        migrations.AlterField(
            model_name='historicalstudent',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, blank=True, editable=False, null=True, populate_from='name', slugify=dms.models.people_model.unicode_slugify, unique_with=['institution'], verbose_name='URL Slug'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, editable=True, populate_from=dms.models.foundation_model.get_institution_slug_source, slugify=dms.models.foundation_model.unicode_slugify, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, blank=True, editable=False, null=True, populate_from='name', slugify=dms.models.people_model.unicode_slugify, unique_with=['institution'], verbose_name='URL Slug'),
        ),
    ]
