# Generated by Django 5.2.7 on 2026-02-17 09:33

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0002_alter_course_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalinstitution',
            name='name_in_english',
        ),
        migrations.RemoveField(
            model_name='institution',
            name='name_in_english',
        ),
        migrations.AddField(
            model_name='historicalinstitution',
            name='name_in_urdu',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='ادارے کا نام اردو میں لکھیں'),
        ),
        migrations.AddField(
            model_name='institution',
            name='name_in_urdu',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='ادارے کا نام اردو میں لکھیں'),
        ),
        migrations.AlterField(
            model_name='historicalinstitution',
            name='name',
            field=models.CharField(max_length=50, verbose_name='ادارے کا نام انگلش میں لکھیں'),
        ),
        migrations.AlterField(
            model_name='historicalinstitution',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, blank=True, editable=True, null=True, populate_from='name'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='name',
            field=models.CharField(max_length=50, verbose_name='ادارے کا نام انگلش میں لکھیں'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, blank=True, editable=True, null=True, populate_from='name', unique=True),
        ),
    ]
