# Generated by Django 5.2.7 on 2026-02-17 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0003_remove_historicalinstitution_name_in_english_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalinstitution',
            name='is_default',
            field=models.BooleanField(default=False, verbose_name='طے شدہ ادارہ'),
        ),
        migrations.AddField(
            model_name='institution',
            name='is_default',
            field=models.BooleanField(default=False, verbose_name='طے شدہ ادارہ'),
        ),
    ]
