# Generated by Django 6.0.2 on 2026-02-18 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0004_historicalinstitution_is_default_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='instructors',
            field=models.ManyToManyField(blank=True, related_name='courses_taught', to='dms.staff', verbose_name='اساتذہ'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('salary', 'تنخواہ'), ('food', 'خوراک/راشن'), ('books', 'کتب و اسٹیشنری'), ('electricity', 'بجلی و برقی اشیاء'), ('maintenance', 'مرمت و تعمیرات'), ('khidmat', 'خدمت خلق'), ('other', 'دیگر')], max_length=50, verbose_name='مد'),
        ),
        migrations.AlterField(
            model_name='historicalexpense',
            name='category',
            field=models.CharField(choices=[('salary', 'تنخواہ'), ('food', 'خوراک/راشن'), ('books', 'کتب و اسٹیشنری'), ('electricity', 'بجلی و برقی اشیاء'), ('maintenance', 'مرمت و تعمیرات'), ('khidmat', 'خدمت خلق'), ('other', 'دیگر')], max_length=50, verbose_name='مد'),
        ),
    ]
