# Generated by Django 5.2.7 on 2026-02-18 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0005_course_instructors_alter_expense_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='receipt_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='واؤچر نمبر'),
        ),
        migrations.AddField(
            model_name='historicalexpense',
            name='receipt_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='واؤچر نمبر'),
        ),
        migrations.AddField(
            model_name='historicalincome',
            name='receipt_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='رسید نمبر'),
        ),
        migrations.AddField(
            model_name='income',
            name='receipt_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='رسید نمبر'),
        ),
    ]
