# Generated by Django 5.2.7 on 2026-02-18 09:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0007_rename_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staff',
            options={'ordering': ('name',), 'verbose_name': 'رکنِ عملہ', 'verbose_name_plural': 'ارکانِ عملہ'},
        ),
        migrations.AddField(
            model_name='historicalparent',
            name='reg_id',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True, verbose_name='رجسٹریشن نمبر'),
        ),
        migrations.AddField(
            model_name='historicalstaff',
            name='reg_id',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True, verbose_name='رجسٹریشن نمبر'),
        ),
        migrations.AddField(
            model_name='historicalstudent',
            name='reg_id',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True, verbose_name='رجسٹریشن نمبر'),
        ),
        migrations.AddField(
            model_name='parent',
            name='reg_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='رجسٹریشن نمبر'),
        ),
        migrations.AddField(
            model_name='staff',
            name='reg_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='رجسٹریشن نمبر'),
        ),
        migrations.AddField(
            model_name='student',
            name='reg_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='رجسٹریشن نمبر'),
        ),
        migrations.AlterField(
            model_name='historicalparent',
            name='address',
            field=models.TextField(blank=True, verbose_name='پتہ'),
        ),
        migrations.AlterField(
            model_name='historicalparent',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='ای میل'),
        ),
        migrations.AlterField(
            model_name='historicalparent',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال ہے؟'),
        ),
        migrations.AlterField(
            model_name='historicalparent',
            name='name',
            field=models.CharField(max_length=200, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='historicalparent',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='فون نمبر'),
        ),
        migrations.AlterField(
            model_name='historicalstaff',
            name='name',
            field=models.CharField(max_length=200, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='historicalstaff',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='فون نمبر'),
        ),
        migrations.AlterField(
            model_name='historicalstudent',
            name='name',
            field=models.CharField(max_length=200, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='historicalstudent',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='فون نمبر'),
        ),
        migrations.AlterField(
            model_name='parent',
            name='address',
            field=models.TextField(blank=True, verbose_name='پتہ'),
        ),
        migrations.AlterField(
            model_name='parent',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='ای میل'),
        ),
        migrations.AlterField(
            model_name='parent',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dms.institution'),
        ),
        migrations.AlterField(
            model_name='parent',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال ہے؟'),
        ),
        migrations.AlterField(
            model_name='parent',
            name='name',
            field=models.CharField(max_length=200, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='parent',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='فون نمبر'),
        ),
        migrations.AlterField(
            model_name='parent',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='staff',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dms.institution'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='name',
            field=models.CharField(max_length=200, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='فون نمبر'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='student',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dms.institution'),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=200, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='فون نمبر'),
        ),
        migrations.AlterField(
            model_name='student',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
