# Generated by Django 5.2.7 on 2026-02-18 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0008_alter_staff_options_historicalparent_reg_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalparent',
            old_name='phone',
            new_name='mobile',
        ),
        migrations.RenameField(
            model_name='historicalstaff',
            old_name='phone',
            new_name='mobile',
        ),
        migrations.RenameField(
            model_name='historicalstudent',
            old_name='phone',
            new_name='mobile',
        ),
        migrations.RenameField(
            model_name='historicalstudent',
            old_name='phone_secondary',
            new_name='mobile2',
        ),
        migrations.RenameField(
            model_name='parent',
            old_name='phone',
            new_name='mobile',
        ),
        migrations.RenameField(
            model_name='staff',
            old_name='phone',
            new_name='mobile',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='phone',
            new_name='mobile',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='phone_secondary',
            new_name='mobile2',
        ),
        migrations.AddField(
            model_name='historicalparent',
            name='mobile2',
            field=models.CharField(blank=True, max_length=20, verbose_name='فون نمبر 2'),
        ),
        migrations.AddField(
            model_name='historicalstaff',
            name='mobile2',
            field=models.CharField(blank=True, max_length=20, verbose_name='فون نمبر 2'),
        ),
        migrations.AddField(
            model_name='parent',
            name='mobile2',
            field=models.CharField(blank=True, max_length=20, verbose_name='فون نمبر 2'),
        ),
        migrations.AddField(
            model_name='staff',
            name='mobile2',
            field=models.CharField(blank=True, max_length=20, verbose_name='فون نمبر 2'),
        ),
    ]
