# Generated by Django 5.2.7 on 2026-02-18 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0009_rename_phone_historicalparent_mobile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalstudent',
            name='roll_no',
        ),
        migrations.RemoveField(
            model_name='student',
            name='roll_no',
        ),
        migrations.AddField(
            model_name='enrollment',
            name='roll_no',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='کلاس رول نمبر'),
        ),
        migrations.AddField(
            model_name='historicalenrollment',
            name='roll_no',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='کلاس رول نمبر'),
        ),
        migrations.AddField(
            model_name='historicalparent',
            name='father_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='والد کا نام'),
        ),
        migrations.AddField(
            model_name='historicalstaff',
            name='father_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='والد کا نام'),
        ),
        migrations.AddField(
            model_name='parent',
            name='father_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='والد کا نام'),
        ),
        migrations.AddField(
            model_name='staff',
            name='father_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='والد کا نام'),
        ),
        migrations.AlterField(
            model_name='historicalparent',
            name='mobile',
            field=models.CharField(blank=True, max_length=20, verbose_name='موبائل نمبر'),
        ),
        migrations.AlterField(
            model_name='historicalparent',
            name='mobile2',
            field=models.CharField(blank=True, max_length=20, verbose_name='موبائل نمبر 2'),
        ),
        migrations.AlterField(
            model_name='historicalstaff',
            name='mobile',
            field=models.CharField(blank=True, max_length=20, verbose_name='موبائل نمبر'),
        ),
        migrations.AlterField(
            model_name='historicalstaff',
            name='mobile2',
            field=models.CharField(blank=True, max_length=20, verbose_name='موبائل نمبر 2'),
        ),
        migrations.AlterField(
            model_name='historicalstudent',
            name='mobile',
            field=models.CharField(blank=True, max_length=20, verbose_name='موبائل نمبر'),
        ),
        migrations.AlterField(
            model_name='historicalstudent',
            name='mobile2',
            field=models.CharField(blank=True, max_length=20, verbose_name='موبائل نمبر 2'),
        ),
        migrations.AlterField(
            model_name='parent',
            name='mobile',
            field=models.CharField(blank=True, max_length=20, verbose_name='موبائل نمبر'),
        ),
        migrations.AlterField(
            model_name='parent',
            name='mobile2',
            field=models.CharField(blank=True, max_length=20, verbose_name='موبائل نمبر 2'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='mobile',
            field=models.CharField(blank=True, max_length=20, verbose_name='موبائل نمبر'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='mobile2',
            field=models.CharField(blank=True, max_length=20, verbose_name='موبائل نمبر 2'),
        ),
        migrations.AlterField(
            model_name='student',
            name='mobile',
            field=models.CharField(blank=True, max_length=20, verbose_name='موبائل نمبر'),
        ),
        migrations.AlterField(
            model_name='student',
            name='mobile2',
            field=models.CharField(blank=True, max_length=20, verbose_name='موبائل نمبر 2'),
        ),
    ]
