# Generated by Django 5.2.7 on 2026-02-18 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0010_remove_historicalstudent_roll_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalparent',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='پتہ'),
        ),
        migrations.AlterField(
            model_name='historicalparent',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='ای میل'),
        ),
        migrations.AlterField(
            model_name='historicalparent',
            name='mobile',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='موبائل نمبر'),
        ),
        migrations.AlterField(
            model_name='historicalparent',
            name='mobile2',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='موبائل نمبر 2'),
        ),
        migrations.AlterField(
            model_name='historicalstaff',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='پتہ'),
        ),
        migrations.AlterField(
            model_name='historicalstaff',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='ای میل'),
        ),
        migrations.AlterField(
            model_name='historicalstaff',
            name='mobile',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='موبائل نمبر'),
        ),
        migrations.AlterField(
            model_name='historicalstaff',
            name='mobile2',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='موبائل نمبر 2'),
        ),
        migrations.AlterField(
            model_name='historicalstudent',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='پتہ'),
        ),
        migrations.AlterField(
            model_name='historicalstudent',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='ای میل'),
        ),
        migrations.AlterField(
            model_name='historicalstudent',
            name='mobile',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='موبائل نمبر'),
        ),
        migrations.AlterField(
            model_name='historicalstudent',
            name='mobile2',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='موبائل نمبر 2'),
        ),
        migrations.AlterField(
            model_name='parent',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='پتہ'),
        ),
        migrations.AlterField(
            model_name='parent',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='ای میل'),
        ),
        migrations.AlterField(
            model_name='parent',
            name='mobile',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='موبائل نمبر'),
        ),
        migrations.AlterField(
            model_name='parent',
            name='mobile2',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='موبائل نمبر 2'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='پتہ'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='ای میل'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='mobile',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='موبائل نمبر'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='mobile2',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='موبائل نمبر 2'),
        ),
        migrations.AlterField(
            model_name='student',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='پتہ'),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='ای میل'),
        ),
        migrations.AlterField(
            model_name='student',
            name='mobile',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='موبائل نمبر'),
        ),
        migrations.AlterField(
            model_name='student',
            name='mobile2',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='موبائل نمبر 2'),
        ),
    ]
