# Generated by Django 5.2.7 on 2026-02-18 11:46

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0011_alter_historicalparent_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalparent',
            name='phone_secondary',
        ),
        migrations.RemoveField(
            model_name='parent',
            name='phone_secondary',
        ),
        migrations.AddField(
            model_name='historicalstaff',
            name='current_advance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='موجودہ ایڈوانس'),
        ),
        migrations.AddField(
            model_name='staff',
            name='current_advance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='موجودہ ایڈوانس'),
        ),
    ]
