# Generated by Django 5.2.7 on 2026-02-20 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0016_alter_announcement_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalparent',
            name='gender',
            field=models.CharField(choices=[('male', 'لڑکا'), ('female', 'لڑکی')], default='male', max_length=10, verbose_name='جنس'),
        ),
        migrations.AddField(
            model_name='historicalstaff',
            name='gender',
            field=models.CharField(choices=[('male', 'لڑکا'), ('female', 'لڑکی')], default='male', max_length=10, verbose_name='جنس'),
        ),
        migrations.AddField(
            model_name='parent',
            name='gender',
            field=models.CharField(choices=[('male', 'لڑکا'), ('female', 'لڑکی')], default='male', max_length=10, verbose_name='جنس'),
        ),
        migrations.AddField(
            model_name='staff',
            name='gender',
            field=models.CharField(choices=[('male', 'لڑکا'), ('female', 'لڑکی')], default='male', max_length=10, verbose_name='جنس'),
        ),
    ]
