# Generated by Django 5.2.7 on 2026-02-24 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0017_historicalparent_gender_historicalstaff_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalincome',
            name='source',
            field=models.CharField(choices=[('Donation', 'عطیہ'), ('Zakat', 'زکوٰۃ'), ('Sadaqah', 'صدقہ'), ('Fitra', 'فطرانہ'), ('Zakat-ul-Fitr', 'صدقہ فطر'), ('Hide', 'کھالیں'), ('Qurbani', 'قربانی'), ('Publication', 'اشاعت/کتب'), ('Rent', 'کرایہ'), ('Event', 'تقریب'), ('Govt Grant', 'سرکاری گرانٹ'), ('Fee', 'فیس'), ('Other', 'دیگر')], default='Donation', max_length=50, verbose_name='ذریعہ'),
        ),
        migrations.AlterField(
            model_name='historicalparent',
            name='reg_id',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=20, null=True, verbose_name='رجسٹریشن نمبر'),
        ),
        migrations.AlterField(
            model_name='historicalstaff',
            name='reg_id',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=20, null=True, verbose_name='رجسٹریشن نمبر'),
        ),
        migrations.AlterField(
            model_name='historicalstaff',
            name='role',
            field=models.CharField(choices=[('imam', 'امام / خطیب'), ('teacher', 'مدرس / استاد'), ('administrator', 'منتظم'), ('accountant', 'خزانچی / ناظم مالیات'), ('academic_head', 'ناظم تعلیمات'), ('support', 'خدمت گار'), ('volunteer', 'رضاکار')], default='teacher', max_length=50, verbose_name='عہدہ'),
        ),
        migrations.AlterField(
            model_name='historicalstudent',
            name='reg_id',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=20, null=True, verbose_name='رجسٹریشن نمبر'),
        ),
        migrations.AlterField(
            model_name='income',
            name='source',
            field=models.CharField(choices=[('Donation', 'عطیہ'), ('Zakat', 'زکوٰۃ'), ('Sadaqah', 'صدقہ'), ('Fitra', 'فطرانہ'), ('Zakat-ul-Fitr', 'صدقہ فطر'), ('Hide', 'کھالیں'), ('Qurbani', 'قربانی'), ('Publication', 'اشاعت/کتب'), ('Rent', 'کرایہ'), ('Event', 'تقریب'), ('Govt Grant', 'سرکاری گرانٹ'), ('Fee', 'فیس'), ('Other', 'دیگر')], default='Donation', max_length=50, verbose_name='ذریعہ'),
        ),
        migrations.AlterField(
            model_name='parent',
            name='reg_id',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True, unique=True, verbose_name='رجسٹریشن نمبر'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='reg_id',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True, unique=True, verbose_name='رجسٹریشن نمبر'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='role',
            field=models.CharField(choices=[('imam', 'امام / خطیب'), ('teacher', 'مدرس / استاد'), ('administrator', 'منتظم'), ('accountant', 'خزانچی / ناظم مالیات'), ('academic_head', 'ناظم تعلیمات'), ('support', 'خدمت گار'), ('volunteer', 'رضاکار')], default='teacher', max_length=50, verbose_name='عہدہ'),
        ),
        migrations.AlterField(
            model_name='student',
            name='reg_id',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True, unique=True, verbose_name='رجسٹریشن نمبر'),
        ),
    ]
