# Generated by Django 6.0.2 on 2026-02-28 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0019_alter_parent_user_alter_staff_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalstaff',
            name='role',
            field=models.CharField(choices=[('president', 'صدر / متولی'), ('vice_president', 'نائب صدر'), ('general_secretary', 'جنرل سیکرٹری / معتمد'), ('joint_secretary', 'جوائنٹ سیکرٹری / نائب معتمد'), ('committee_member', 'رکن کمیٹی / ممبر شوریٰ'), ('administrator', 'سسٹم منتظم / Admin'), ('accountant', 'خزانچی / ناظم مالیات'), ('academic_head', 'مہتمم / ناظم تعلیمات'), ('imam', 'امام / خطیب'), ('muezzin', 'مؤذن'), ('teacher', 'مدرس / استاد'), ('support', 'خادم / خدمت گار'), ('volunteer', 'رضاکار')], default='teacher', max_length=50, verbose_name='عہدہ'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='role',
            field=models.CharField(choices=[('president', 'صدر / متولی'), ('vice_president', 'نائب صدر'), ('general_secretary', 'جنرل سیکرٹری / معتمد'), ('joint_secretary', 'جوائنٹ سیکرٹری / نائب معتمد'), ('committee_member', 'رکن کمیٹی / ممبر شوریٰ'), ('administrator', 'سسٹم منتظم / Admin'), ('accountant', 'خزانچی / ناظم مالیات'), ('academic_head', 'مہتمم / ناظم تعلیمات'), ('imam', 'امام / خطیب'), ('muezzin', 'مؤذن'), ('teacher', 'مدرس / استاد'), ('support', 'خادم / خدمت گار'), ('volunteer', 'رضاکار')], default='teacher', max_length=50, verbose_name='عہدہ'),
        ),
    ]
