"""Add course_code and sync schema

Revision ID: 324e47216e0a
Revises: 7b58ae4bf543
Create Date: 2026-03-05 14:13:24.982680

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '324e47216e0a'
down_revision: Union[str, Sequence[str], None] = '7b58ae4bf543'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dms_announcement', schema=None) as batch_op:
        batch_op.alter_column('institution_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               nullable=True)
        batch_op.alter_column('content',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
        batch_op.drop_index('dms_announcement_deleted_63ff422e')
        batch_op.drop_index('dms_announcement_institution_id_f7a1926a')
        batch_op.drop_column('deleted')

    with op.batch_alter_table('dms_announcement_target_parents', schema=None) as batch_op:
        batch_op.alter_column('announcement_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
        batch_op.alter_column('parent_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
        batch_op.drop_index('dms_announcement_target_parents_announcement_id_46fcf75d')
        batch_op.drop_index('dms_announcement_target_parents_announcement_id_parent_id_d1d6a2e5_uniq')
        batch_op.drop_index('dms_announcement_target_parents_parent_id_75308d2c')
        batch_op.drop_column('id')

    with op.batch_alter_table('dms_assetissue', schema=None) as batch_op:
        batch_op.alter_column('item_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
        batch_op.alter_column('student_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.alter_column('staff_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.alter_column('notes',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
        batch_op.drop_index('dms_assetissue_deleted_76ee76a7')
        batch_op.drop_index('dms_assetissue_item_id_2ce1d84f')
        batch_op.drop_index('dms_assetissue_staff_id_6da353c0')
        batch_op.drop_index('dms_assetissue_student_id_85529473')
        batch_op.drop_column('deleted')

    with op.batch_alter_table('dms_attendance', schema=None) as batch_op:
        batch_op.alter_column('institution_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               nullable=True)
        batch_op.alter_column('session_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
        batch_op.alter_column('student_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
        batch_op.alter_column('remarks',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
        batch_op.drop_index('dms_attendance_deleted_d720baab')
        batch_op.drop_index('dms_attendance_institution_id_e442e6d4')
        batch_op.drop_index('dms_attendance_session_id_75a27e19')
        batch_op.drop_index('dms_attendance_session_id_student_id_29dbd19f_uniq')
        batch_op.drop_index('dms_attendance_student_id_ddc4cfd5')
        batch_op.create_unique_constraint('uq_student_attendance', ['session_id', 'student_id'])
        batch_op.drop_column('deleted')

    with op.batch_alter_table('dms_backup', schema=None) as batch_op:
        batch_op.drop_column('deleted_at')

    with op.batch_alter_table('dms_classsession', schema=None) as batch_op:
        batch_op.alter_column('course_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
        batch_op.alter_column('notes',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
        batch_op.drop_index('dms_classsession_course_id_89304d11')
        batch_op.drop_index('dms_classsession_date_a4348207')
        batch_op.drop_index('dms_classsession_deleted_9bde839f')
        batch_op.create_index(batch_op.f('ix_dms_classsession_date'), ['date'], unique=False)
        batch_op.create_unique_constraint('uq_course_session', ['course_id', 'date', 'start_time'])
        batch_op.drop_column('deleted')

    with op.batch_alter_table('dms_course', schema=None) as batch_op:
        batch_op.add_column(sa.Column('course_code', sqlmodel.sql.sqltypes.AutoString(length=25), nullable=True))
        batch_op.alter_column('institution_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               nullable=True)
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
        batch_op.alter_column('admission_fee',
               existing_type=sa.DECIMAL(),
               type_=sa.Float(),
               existing_nullable=False)
        batch_op.alter_column('course_fee',
               existing_type=sa.DECIMAL(),
               type_=sa.Float(),
               existing_nullable=False)
        batch_op.drop_index('dms_course_deleted_75b88d49')
        batch_op.drop_index('dms_course_institution_id_fa008cc3')
        batch_op.create_index(batch_op.f('ix_dms_course_course_code'), ['course_code'], unique=False)
        batch_op.drop_column('deleted')

    with op.batch_alter_table('dms_course_instructors', schema=None) as batch_op:
        batch_op.alter_column('course_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
        batch_op.alter_column('staff_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
        batch_op.drop_index('dms_course_instructors_course_id_e18d3aa4')
        batch_op.drop_index('dms_course_instructors_course_id_staff_id_935cc61b_uniq')
        batch_op.drop_index('dms_course_instructors_staff_id_c1231d22')
        batch_op.drop_column('id')

    with op.batch_alter_table('dms_donor', schema=None) as batch_op:
        batch_op.alter_column('institution_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               nullable=True)
        batch_op.alter_column('address',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
        batch_op.drop_index('dms_donor_deleted_2ba14ea9')
        batch_op.drop_index('dms_donor_institution_id_be3ea0e3')
        batch_op.drop_column('deleted')

    with op.batch_alter_table('dms_enrollment', schema=None) as batch_op:
        batch_op.alter_column('student_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
        batch_op.alter_column('course_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
        batch_op.alter_column('enrollment_date',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.alter_column('admission_fee_discount',
               existing_type=sa.DECIMAL(),
               type_=sa.Float(),
               nullable=True)
        batch_op.alter_column('agreed_admission_fee',
               existing_type=sa.DECIMAL(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('course_fee_discount',
               existing_type=sa.DECIMAL(),
               type_=sa.Float(),
               nullable=True)
        batch_op.alter_column('agreed_course_fee',
               existing_type=sa.DECIMAL(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.drop_index('dms_enrollment_course_id_bf2428c8')
        batch_op.drop_index('dms_enrollment_deleted_b0643f71')
        batch_op.drop_index('dms_enrollment_student_id_5631c489')
        batch_op.drop_index('dms_enrollment_student_id_course_id_2f487656_uniq')
        batch_op.create_unique_constraint('uq_active_admission', ['student_id', 'course_id', 'status'])
        batch_op.drop_column('deleted')

    with op.batch_alter_table('dms_exam', schema=None) as batch_op:
        batch_op.alter_column('institution_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               nullable=True)
        batch_op.alter_column('notes',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
        batch_op.drop_index('dms_exam_deleted_d2ef8eb2')
        batch_op.drop_index('dms_exam_institution_id_67dc388e')
        batch_op.drop_column('deleted')

    with op.batch_alter_table('dms_examresult', schema=None) as batch_op:
        batch_op.alter_column('exam_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
        batch_op.alter_column('student_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
        batch_op.alter_column('course_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
        batch_op.drop_index('dms_examresult_course_id_d98b30f7')
        batch_op.drop_index('dms_examresult_deleted_c9c1fb25')
        batch_op.drop_index('dms_examresult_exam_id_9c7faa56')
        batch_op.drop_index('dms_examresult_exam_id_student_id_course_id_8864505f_uniq')
        batch_op.drop_index('dms_examresult_student_id_b9727676')
        batch_op.drop_column('deleted')

    with op.batch_alter_table('dms_expense', schema=None) as batch_op:
        batch_op.alter_column('institution_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               nullable=True)
        batch_op.alter_column('amount',
               existing_type=sa.DECIMAL(),
               type_=sa.Float(),
               nullable=True)
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
        batch_op.drop_index('dms_expense_deleted_190bf8c3')
        batch_op.drop_index('dms_expense_institu_4c9a81_idx')
        batch_op.drop_index('dms_expense_institution_id_81752702')
        batch_op.drop_column('deleted')

    with op.batch_alter_table('dms_facility', schema=None) as batch_op:
        batch_op.alter_column('institution_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               nullable=True)
        batch_op.drop_index('dms_facility_deleted_187c51c4')
        batch_op.drop_index('dms_facility_institution_id_74ae4783')
        batch_op.drop_column('deleted')

    with op.batch_alter_table('dms_fee', schema=None) as batch_op:
        batch_op.alter_column('institution_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               nullable=True)
        batch_op.alter_column('student_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
        batch_op.alter_column('course_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.alter_column('enrollment_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.alter_column('amount_due',
               existing_type=sa.DECIMAL(),
               type_=sa.Float(),
               nullable=True)
        batch_op.alter_column('amount_paid',
               existing_type=sa.DECIMAL(),
               type_=sa.Float(),
               nullable=True)
        batch_op.alter_column('discount',
               existing_type=sa.DECIMAL(),
               type_=sa.Float(),
               nullable=True)
        batch_op.alter_column('late_fee',
               existing_type=sa.DECIMAL(),
               type_=sa.Float(),
               nullable=True)
        batch_op.drop_index('dms_fee_course_id_5112e03b')
        batch_op.drop_index('dms_fee_deleted_2e68811c')
        batch_op.drop_index('dms_fee_enrollment_id_1bb8174d')
        batch_op.drop_index('dms_fee_institu_c29ef5_idx')
        batch_op.drop_index('dms_fee_institution_id_bc72a5ef')
        batch_op.drop_index('dms_fee_student_id_25c10b0d')
        batch_op.drop_column('deleted')

    with op.batch_alter_table('dms_fee_payment', schema=None) as batch_op:
        batch_op.alter_column('institution_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               nullable=True)
        batch_op.alter_column('student_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
        batch_op.alter_column('fee_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.alter_column('amount',
               existing_type=sa.DECIMAL(),
               type_=sa.Float(),
               nullable=True)
        batch_op.drop_index('dms_fee_pay_institu_f92d64_idx')
        batch_op.drop_index('dms_fee_payment_deleted_149ae1df')
        batch_op.drop_index('dms_fee_payment_fee_id_d3f49101')
        batch_op.drop_index('dms_fee_payment_institution_id_7d2d4aa5')
        batch_op.drop_index('dms_fee_payment_student_id_9df87345')
        batch_op.create_index(batch_op.f('ix_dms_fee_payment_receipt_number'), ['receipt_number'], unique=True)
        batch_op.drop_column('deleted')

    with op.batch_alter_table('dms_income', schema=None) as batch_op:
        batch_op.alter_column('institution_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               nullable=True)
        batch_op.alter_column('payment_record_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.alter_column('donor_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.alter_column('amount',
               existing_type=sa.DECIMAL(),
               type_=sa.Float(),
               nullable=True)
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
        batch_op.drop_index('dms_income_deleted_c0964bd5')
        batch_op.drop_index('dms_income_donor_id_85d3e069')
        batch_op.drop_index('dms_income_institu_403220_idx')
        batch_op.drop_index('dms_income_institution_id_294b3e28')
        batch_op.drop_column('deleted')

    with op.batch_alter_table('dms_institution', schema=None) as batch_op:
        batch_op.alter_column('slug',
               existing_type=sa.VARCHAR(length=50),
               type_=sqlmodel.sql.sqltypes.AutoString(length=255),
               existing_nullable=True)
        batch_op.alter_column('address',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
        batch_op.drop_index('dms_institution_deleted_ef223337')
        batch_op.drop_index('dms_institution_user_id_1b45e642')
        batch_op.create_index(batch_op.f('ix_dms_institution_reg_id'), ['reg_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_dms_institution_slug'), ['slug'], unique=False)
        batch_op.drop_column('deleted')

    with op.batch_alter_table('dms_inventoryitem', schema=None) as batch_op:
        batch_op.alter_column('institution_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               nullable=True)
        batch_op.alter_column('category_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.alter_column('price',
               existing_type=sa.DECIMAL(),
               type_=sa.Float(),
               nullable=True)
        batch_op.drop_index('dms_inventoryitem_category_id_29497fc6')
        batch_op.drop_index('dms_inventoryitem_deleted_9e581a9a')
        batch_op.drop_index('dms_inventoryitem_institution_id_d4a3def7')
        batch_op.drop_column('deleted')

    with op.batch_alter_table('dms_itemcategory', schema=None) as batch_op:
        batch_op.alter_column('institution_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               nullable=True)
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
        batch_op.drop_index('dms_itemcategory_deleted_4bbfee51')
        batch_op.drop_index('dms_itemcategory_institution_id_96a13766')
        batch_op.drop_column('deleted')

    with op.batch_alter_table('dms_parent', schema=None) as batch_op:
        batch_op.add_column(sa.Column('family_id', sqlmodel.sql.sqltypes.AutoString(length=25), nullable=True))
        batch_op.alter_column('address',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
        batch_op.alter_column('institution_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               nullable=True)
        batch_op.drop_index('dms_parent_deleted_d8ac691a')
        batch_op.drop_index('dms_parent_institution_id_d00c6d5a')
        batch_op.create_index(batch_op.f('ix_dms_parent_family_id'), ['family_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_dms_parent_reg_id'), ['reg_id'], unique=False)
        batch_op.drop_column('deleted')

    with op.batch_alter_table('dms_staff', schema=None) as batch_op:
        batch_op.alter_column('address',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
        batch_op.alter_column('institution_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               nullable=True)
        batch_op.alter_column('base_salary',
               existing_type=sa.DECIMAL(),
               type_=sa.Float(),
               nullable=True)
        batch_op.alter_column('current_advance',
               existing_type=sa.DECIMAL(),
               type_=sa.Float(),
               nullable=True)
        batch_op.alter_column('notes',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
        batch_op.drop_index('dms_staff_deleted_67256f1e')
        batch_op.drop_index('dms_staff_institution_id_7df754fa')
        batch_op.create_index(batch_op.f('ix_dms_staff_reg_id'), ['reg_id'], unique=False)
        batch_op.drop_column('deleted')

    with op.batch_alter_table('dms_staff_attendance', schema=None) as batch_op:
        batch_op.alter_column('institution_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               nullable=True)
        batch_op.alter_column('staff_member_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
        batch_op.alter_column('remarks',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
        batch_op.drop_index('dms_staff_attendance_date_861b9d19')
        batch_op.drop_index('dms_staff_attendance_deleted_39f4f950')
        batch_op.drop_index('dms_staff_attendance_institution_id_0911441c')
        batch_op.drop_index('dms_staff_attendance_staff_member_id_8b4cc1ad')
        batch_op.drop_index('dms_staff_attendance_staff_member_id_date_9259a498_uniq')
        batch_op.create_index(batch_op.f('ix_dms_staff_attendance_date'), ['date'], unique=False)
        batch_op.drop_column('deleted')

    with op.batch_alter_table('dms_staffadvance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('institution_id', sa.Integer(), nullable=True))
        batch_op.alter_column('staff_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
        batch_op.alter_column('amount',
               existing_type=sa.DECIMAL(),
               type_=sa.Float(),
               nullable=True)
        batch_op.drop_index('dms_staffadvance_staff_id_0b0d01df')
        batch_op.create_foreign_key('fk_staffadvance_institution', 'dms_institution', ['institution_id'], ['id'])

    with op.batch_alter_table('dms_student', schema=None) as batch_op:
        batch_op.alter_column('address',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
        batch_op.alter_column('institution_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               nullable=True)
        batch_op.alter_column('slug',
               existing_type=sa.VARCHAR(length=50),
               type_=sqlmodel.sql.sqltypes.AutoString(length=255),
               existing_nullable=True)
        batch_op.alter_column('notes',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
        batch_op.alter_column('wallet_balance',
               existing_type=sa.DECIMAL(),
               type_=sa.Float(),
               nullable=True)
        batch_op.alter_column('enrollment_date',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.drop_index('dms_student_deleted_7bcc0a9b')
        batch_op.drop_index('dms_student_institution_id_7cae7b03')
        batch_op.drop_index('dms_student_slug_2d00a330')
        batch_op.create_index(batch_op.f('ix_dms_student_reg_id'), ['reg_id'], unique=False)
        batch_op.create_unique_constraint('uq_student_reg_id', ['institution_id', 'reg_id'])
        batch_op.drop_column('deleted')

    with op.batch_alter_table('dms_student_parents', schema=None) as batch_op:
        batch_op.alter_column('student_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
        batch_op.alter_column('parent_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
        batch_op.drop_index('dms_student_parents_parent_id_31a6d184')
        batch_op.drop_index('dms_student_parents_student_id_4193d979')
        batch_op.drop_index('dms_student_parents_student_id_parent_id_fe3ab470_uniq')
        batch_op.drop_column('id')

    with op.batch_alter_table('dms_timetableitem', schema=None) as batch_op:
        batch_op.alter_column('institution_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               nullable=True)
        batch_op.alter_column('course_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
        batch_op.alter_column('teacher_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.alter_column('facility_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.drop_index('dms_timetableitem_course_id_aa5c7fd4')
        batch_op.drop_index('dms_timetableitem_deleted_3d521c5c')
        batch_op.drop_index('dms_timetableitem_facility_id_ec82ed4c')
        batch_op.drop_index('dms_timetableitem_institution_id_c454d1a6')
        batch_op.drop_index('dms_timetableitem_teacher_id_935a5293')
        batch_op.drop_column('deleted')

    with op.batch_alter_table('dms_wallettransaction', schema=None) as batch_op:
        batch_op.alter_column('student_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
        batch_op.alter_column('amount',
               existing_type=sa.DECIMAL(),
               type_=sa.Float(),
               nullable=True)
        batch_op.alter_column('payment_ref_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.drop_index('dms_wallettransaction_deleted_eebee506')
        batch_op.drop_index('dms_wallettransaction_payment_ref_id_56128e9f')
        batch_op.drop_index('dms_wallettransaction_student_id_023cd790')
        batch_op.drop_column('deleted')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dms_wallettransaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted', sa.DATETIME(), nullable=True))
        batch_op.create_index('dms_wallettransaction_student_id_023cd790', ['student_id'], unique=False)
        batch_op.create_index('dms_wallettransaction_payment_ref_id_56128e9f', ['payment_ref_id'], unique=False)
        batch_op.create_index('dms_wallettransaction_deleted_eebee506', ['deleted'], unique=False)
        batch_op.alter_column('payment_ref_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
        batch_op.alter_column('amount',
               existing_type=sa.Float(),
               type_=sa.DECIMAL(),
               nullable=False)
        batch_op.alter_column('student_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)

    with op.batch_alter_table('dms_timetableitem', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted', sa.DATETIME(), nullable=True))
        batch_op.create_index('dms_timetableitem_teacher_id_935a5293', ['teacher_id'], unique=False)
        batch_op.create_index('dms_timetableitem_institution_id_c454d1a6', ['institution_id'], unique=False)
        batch_op.create_index('dms_timetableitem_facility_id_ec82ed4c', ['facility_id'], unique=False)
        batch_op.create_index('dms_timetableitem_deleted_3d521c5c', ['deleted'], unique=False)
        batch_op.create_index('dms_timetableitem_course_id_aa5c7fd4', ['course_id'], unique=False)
        batch_op.alter_column('facility_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
        batch_op.alter_column('teacher_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
        batch_op.alter_column('course_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
        batch_op.alter_column('institution_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               nullable=False)

    with op.batch_alter_table('dms_student_parents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.INTEGER(), nullable=False))
        batch_op.create_index('dms_student_parents_student_id_parent_id_fe3ab470_uniq', ['student_id', 'parent_id'], unique=1)
        batch_op.create_index('dms_student_parents_student_id_4193d979', ['student_id'], unique=False)
        batch_op.create_index('dms_student_parents_parent_id_31a6d184', ['parent_id'], unique=False)
        batch_op.alter_column('parent_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
        batch_op.alter_column('student_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)

    with op.batch_alter_table('dms_student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted', sa.DATETIME(), nullable=True))
        batch_op.drop_constraint('uq_student_reg_id', type_='unique')
        batch_op.drop_index(batch_op.f('ix_dms_student_reg_id'))
        batch_op.create_index('dms_student_slug_2d00a330', ['slug'], unique=False)
        batch_op.create_index('dms_student_institution_id_7cae7b03', ['institution_id'], unique=False)
        batch_op.create_index('dms_student_deleted_7bcc0a9b', ['deleted'], unique=False)
        batch_op.alter_column('enrollment_date',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.alter_column('wallet_balance',
               existing_type=sa.Float(),
               type_=sa.DECIMAL(),
               nullable=False)
        batch_op.alter_column('notes',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('slug',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=255),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.alter_column('institution_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               nullable=False)
        batch_op.alter_column('address',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('dms_staffadvance', schema=None) as batch_op:
        batch_op.drop_constraint('fk_staffadvance_institution', type_='foreignkey')
        batch_op.create_index('dms_staffadvance_staff_id_0b0d01df', ['staff_id'], unique=False)
        batch_op.alter_column('amount',
               existing_type=sa.Float(),
               type_=sa.DECIMAL(),
               nullable=False)
        batch_op.alter_column('staff_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
        batch_op.drop_column('institution_id')

    with op.batch_alter_table('dms_staff_attendance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted', sa.DATETIME(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_dms_staff_attendance_date'))
        batch_op.create_index('dms_staff_attendance_staff_member_id_date_9259a498_uniq', ['staff_member_id', 'date'], unique=1)
        batch_op.create_index('dms_staff_attendance_staff_member_id_8b4cc1ad', ['staff_member_id'], unique=False)
        batch_op.create_index('dms_staff_attendance_institution_id_0911441c', ['institution_id'], unique=False)
        batch_op.create_index('dms_staff_attendance_deleted_39f4f950', ['deleted'], unique=False)
        batch_op.create_index('dms_staff_attendance_date_861b9d19', ['date'], unique=False)
        batch_op.alter_column('remarks',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('staff_member_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
        batch_op.alter_column('institution_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               nullable=False)

    with op.batch_alter_table('dms_staff', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted', sa.DATETIME(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_dms_staff_reg_id'))
        batch_op.create_index('dms_staff_institution_id_7df754fa', ['institution_id'], unique=False)
        batch_op.create_index('dms_staff_deleted_67256f1e', ['deleted'], unique=False)
        batch_op.alter_column('notes',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('current_advance',
               existing_type=sa.Float(),
               type_=sa.DECIMAL(),
               nullable=False)
        batch_op.alter_column('base_salary',
               existing_type=sa.Float(),
               type_=sa.DECIMAL(),
               nullable=False)
        batch_op.alter_column('institution_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               nullable=False)
        batch_op.alter_column('address',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('dms_parent', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted', sa.DATETIME(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_dms_parent_reg_id'))
        batch_op.drop_index(batch_op.f('ix_dms_parent_family_id'))
        batch_op.create_index('dms_parent_institution_id_d00c6d5a', ['institution_id'], unique=False)
        batch_op.create_index('dms_parent_deleted_d8ac691a', ['deleted'], unique=False)
        batch_op.alter_column('institution_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               nullable=False)
        batch_op.alter_column('address',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.drop_column('family_id')

    with op.batch_alter_table('dms_itemcategory', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted', sa.DATETIME(), nullable=True))
        batch_op.create_index('dms_itemcategory_institution_id_96a13766', ['institution_id'], unique=False)
        batch_op.create_index('dms_itemcategory_deleted_4bbfee51', ['deleted'], unique=False)
        batch_op.alter_column('description',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('institution_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               nullable=False)

    with op.batch_alter_table('dms_inventoryitem', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted', sa.DATETIME(), nullable=True))
        batch_op.create_index('dms_inventoryitem_institution_id_d4a3def7', ['institution_id'], unique=False)
        batch_op.create_index('dms_inventoryitem_deleted_9e581a9a', ['deleted'], unique=False)
        batch_op.create_index('dms_inventoryitem_category_id_29497fc6', ['category_id'], unique=False)
        batch_op.alter_column('price',
               existing_type=sa.Float(),
               type_=sa.DECIMAL(),
               nullable=False)
        batch_op.alter_column('category_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
        batch_op.alter_column('institution_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               nullable=False)

    with op.batch_alter_table('dms_institution', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted', sa.DATETIME(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_dms_institution_slug'))
        batch_op.drop_index(batch_op.f('ix_dms_institution_reg_id'))
        batch_op.create_index('dms_institution_user_id_1b45e642', ['user_id'], unique=False)
        batch_op.create_index('dms_institution_deleted_ef223337', ['deleted'], unique=False)
        batch_op.alter_column('address',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('slug',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=255),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)

    with op.batch_alter_table('dms_income', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted', sa.DATETIME(), nullable=True))
        batch_op.create_index('dms_income_institution_id_294b3e28', ['institution_id'], unique=False)
        batch_op.create_index('dms_income_institu_403220_idx', ['institution_id', 'date'], unique=False)
        batch_op.create_index('dms_income_donor_id_85d3e069', ['donor_id'], unique=False)
        batch_op.create_index('dms_income_deleted_c0964bd5', ['deleted'], unique=False)
        batch_op.alter_column('description',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('amount',
               existing_type=sa.Float(),
               type_=sa.DECIMAL(),
               nullable=False)
        batch_op.alter_column('donor_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
        batch_op.alter_column('payment_record_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
        batch_op.alter_column('institution_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               nullable=False)

    with op.batch_alter_table('dms_fee_payment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted', sa.DATETIME(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_dms_fee_payment_receipt_number'))
        batch_op.create_index('dms_fee_payment_student_id_9df87345', ['student_id'], unique=False)
        batch_op.create_index('dms_fee_payment_institution_id_7d2d4aa5', ['institution_id'], unique=False)
        batch_op.create_index('dms_fee_payment_fee_id_d3f49101', ['fee_id'], unique=False)
        batch_op.create_index('dms_fee_payment_deleted_149ae1df', ['deleted'], unique=False)
        batch_op.create_index('dms_fee_pay_institu_f92d64_idx', ['institution_id', 'payment_date'], unique=False)
        batch_op.alter_column('amount',
               existing_type=sa.Float(),
               type_=sa.DECIMAL(),
               nullable=False)
        batch_op.alter_column('fee_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
        batch_op.alter_column('student_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
        batch_op.alter_column('institution_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               nullable=False)

    with op.batch_alter_table('dms_fee', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted', sa.DATETIME(), nullable=True))
        batch_op.create_index('dms_fee_student_id_25c10b0d', ['student_id'], unique=False)
        batch_op.create_index('dms_fee_institution_id_bc72a5ef', ['institution_id'], unique=False)
        batch_op.create_index('dms_fee_institu_c29ef5_idx', ['institution_id', 'status'], unique=False)
        batch_op.create_index('dms_fee_enrollment_id_1bb8174d', ['enrollment_id'], unique=False)
        batch_op.create_index('dms_fee_deleted_2e68811c', ['deleted'], unique=False)
        batch_op.create_index('dms_fee_course_id_5112e03b', ['course_id'], unique=False)
        batch_op.alter_column('late_fee',
               existing_type=sa.Float(),
               type_=sa.DECIMAL(),
               nullable=False)
        batch_op.alter_column('discount',
               existing_type=sa.Float(),
               type_=sa.DECIMAL(),
               nullable=False)
        batch_op.alter_column('amount_paid',
               existing_type=sa.Float(),
               type_=sa.DECIMAL(),
               nullable=False)
        batch_op.alter_column('amount_due',
               existing_type=sa.Float(),
               type_=sa.DECIMAL(),
               nullable=False)
        batch_op.alter_column('enrollment_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
        batch_op.alter_column('course_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
        batch_op.alter_column('student_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
        batch_op.alter_column('institution_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               nullable=False)

    with op.batch_alter_table('dms_facility', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted', sa.DATETIME(), nullable=True))
        batch_op.create_index('dms_facility_institution_id_74ae4783', ['institution_id'], unique=False)
        batch_op.create_index('dms_facility_deleted_187c51c4', ['deleted'], unique=False)
        batch_op.alter_column('institution_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               nullable=False)

    with op.batch_alter_table('dms_expense', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted', sa.DATETIME(), nullable=True))
        batch_op.create_index('dms_expense_institution_id_81752702', ['institution_id'], unique=False)
        batch_op.create_index('dms_expense_institu_4c9a81_idx', ['institution_id', 'date'], unique=False)
        batch_op.create_index('dms_expense_deleted_190bf8c3', ['deleted'], unique=False)
        batch_op.alter_column('description',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('amount',
               existing_type=sa.Float(),
               type_=sa.DECIMAL(),
               nullable=False)
        batch_op.alter_column('institution_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               nullable=False)

    with op.batch_alter_table('dms_examresult', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted', sa.DATETIME(), nullable=True))
        batch_op.create_index('dms_examresult_student_id_b9727676', ['student_id'], unique=False)
        batch_op.create_index('dms_examresult_exam_id_student_id_course_id_8864505f_uniq', ['exam_id', 'student_id', 'course_id'], unique=1)
        batch_op.create_index('dms_examresult_exam_id_9c7faa56', ['exam_id'], unique=False)
        batch_op.create_index('dms_examresult_deleted_c9c1fb25', ['deleted'], unique=False)
        batch_op.create_index('dms_examresult_course_id_d98b30f7', ['course_id'], unique=False)
        batch_op.alter_column('course_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
        batch_op.alter_column('student_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
        batch_op.alter_column('exam_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)

    with op.batch_alter_table('dms_exam', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted', sa.DATETIME(), nullable=True))
        batch_op.create_index('dms_exam_institution_id_67dc388e', ['institution_id'], unique=False)
        batch_op.create_index('dms_exam_deleted_d2ef8eb2', ['deleted'], unique=False)
        batch_op.alter_column('notes',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('institution_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               nullable=False)

    with op.batch_alter_table('dms_enrollment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted', sa.DATETIME(), nullable=True))
        batch_op.drop_constraint('uq_active_admission', type_='unique')
        batch_op.create_index('dms_enrollment_student_id_course_id_2f487656_uniq', ['student_id', 'course_id'], unique=1)
        batch_op.create_index('dms_enrollment_student_id_5631c489', ['student_id'], unique=False)
        batch_op.create_index('dms_enrollment_deleted_b0643f71', ['deleted'], unique=False)
        batch_op.create_index('dms_enrollment_course_id_bf2428c8', ['course_id'], unique=False)
        batch_op.alter_column('agreed_course_fee',
               existing_type=sa.Float(),
               type_=sa.DECIMAL(),
               existing_nullable=True)
        batch_op.alter_column('course_fee_discount',
               existing_type=sa.Float(),
               type_=sa.DECIMAL(),
               nullable=False)
        batch_op.alter_column('agreed_admission_fee',
               existing_type=sa.Float(),
               type_=sa.DECIMAL(),
               existing_nullable=True)
        batch_op.alter_column('admission_fee_discount',
               existing_type=sa.Float(),
               type_=sa.DECIMAL(),
               nullable=False)
        batch_op.alter_column('enrollment_date',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.alter_column('course_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
        batch_op.alter_column('student_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)

    with op.batch_alter_table('dms_donor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted', sa.DATETIME(), nullable=True))
        batch_op.create_index('dms_donor_institution_id_be3ea0e3', ['institution_id'], unique=False)
        batch_op.create_index('dms_donor_deleted_2ba14ea9', ['deleted'], unique=False)
        batch_op.alter_column('address',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('institution_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               nullable=False)

    with op.batch_alter_table('dms_course_instructors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.INTEGER(), nullable=False))
        batch_op.create_index('dms_course_instructors_staff_id_c1231d22', ['staff_id'], unique=False)
        batch_op.create_index('dms_course_instructors_course_id_staff_id_935cc61b_uniq', ['course_id', 'staff_id'], unique=1)
        batch_op.create_index('dms_course_instructors_course_id_e18d3aa4', ['course_id'], unique=False)
        batch_op.alter_column('staff_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
        batch_op.alter_column('course_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)

    with op.batch_alter_table('dms_course', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted', sa.DATETIME(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_dms_course_course_code'))
        batch_op.create_index('dms_course_institution_id_fa008cc3', ['institution_id'], unique=False)
        batch_op.create_index('dms_course_deleted_75b88d49', ['deleted'], unique=False)
        batch_op.alter_column('course_fee',
               existing_type=sa.Float(),
               type_=sa.DECIMAL(),
               existing_nullable=False)
        batch_op.alter_column('admission_fee',
               existing_type=sa.Float(),
               type_=sa.DECIMAL(),
               existing_nullable=False)
        batch_op.alter_column('description',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('institution_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               nullable=False)
        batch_op.drop_column('course_code')

    with op.batch_alter_table('dms_classsession', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted', sa.DATETIME(), nullable=True))
        batch_op.drop_constraint('uq_course_session', type_='unique')
        batch_op.drop_index(batch_op.f('ix_dms_classsession_date'))
        batch_op.create_index('dms_classsession_deleted_9bde839f', ['deleted'], unique=False)
        batch_op.create_index('dms_classsession_date_a4348207', ['date'], unique=False)
        batch_op.create_index('dms_classsession_course_id_89304d11', ['course_id'], unique=False)
        batch_op.alter_column('notes',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('course_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)

    with op.batch_alter_table('dms_backup', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', sa.DATETIME(), nullable=True))

    with op.batch_alter_table('dms_attendance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted', sa.DATETIME(), nullable=True))
        batch_op.drop_constraint('uq_student_attendance', type_='unique')
        batch_op.create_index('dms_attendance_student_id_ddc4cfd5', ['student_id'], unique=False)
        batch_op.create_index('dms_attendance_session_id_student_id_29dbd19f_uniq', ['session_id', 'student_id'], unique=1)
        batch_op.create_index('dms_attendance_session_id_75a27e19', ['session_id'], unique=False)
        batch_op.create_index('dms_attendance_institution_id_e442e6d4', ['institution_id'], unique=False)
        batch_op.create_index('dms_attendance_deleted_d720baab', ['deleted'], unique=False)
        batch_op.alter_column('remarks',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('student_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
        batch_op.alter_column('session_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
        batch_op.alter_column('institution_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               nullable=False)

    with op.batch_alter_table('dms_assetissue', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted', sa.DATETIME(), nullable=True))
        batch_op.create_index('dms_assetissue_student_id_85529473', ['student_id'], unique=False)
        batch_op.create_index('dms_assetissue_staff_id_6da353c0', ['staff_id'], unique=False)
        batch_op.create_index('dms_assetissue_item_id_2ce1d84f', ['item_id'], unique=False)
        batch_op.create_index('dms_assetissue_deleted_76ee76a7', ['deleted'], unique=False)
        batch_op.alter_column('notes',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('staff_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
        batch_op.alter_column('student_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
        batch_op.alter_column('item_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)

    with op.batch_alter_table('dms_announcement_target_parents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.INTEGER(), nullable=False))
        batch_op.create_index('dms_announcement_target_parents_parent_id_75308d2c', ['parent_id'], unique=False)
        batch_op.create_index('dms_announcement_target_parents_announcement_id_parent_id_d1d6a2e5_uniq', ['announcement_id', 'parent_id'], unique=1)
        batch_op.create_index('dms_announcement_target_parents_announcement_id_46fcf75d', ['announcement_id'], unique=False)
        batch_op.alter_column('parent_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
        batch_op.alter_column('announcement_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)

    with op.batch_alter_table('dms_announcement', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted', sa.DATETIME(), nullable=True))
        batch_op.create_index('dms_announcement_institution_id_f7a1926a', ['institution_id'], unique=False)
        batch_op.create_index('dms_announcement_deleted_63ff422e', ['deleted'], unique=False)
        batch_op.alter_column('content',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('institution_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               nullable=False)

    # ### end Alembic commands ###
