"""Add Daily Attendance

Revision ID: 87b69b66e323
Revises: 324e47216e0a
Create Date: 2026-03-05 19:33:13.767466

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '87b69b66e323'
down_revision: Union[str, Sequence[str], None] = '324e47216e0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dms_daily_attendance',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by_cascade', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('institution_id', sa.Integer(), nullable=True),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('remarks', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['institution_id'], ['dms_institution.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['dms_student.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'date', name='uq_student_daily_attendance')
    )
    with op.batch_alter_table('dms_daily_attendance', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dms_daily_attendance_date'), ['date'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dms_daily_attendance', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dms_daily_attendance_date'))

    op.drop_table('dms_daily_attendance')
    # ### end Alembic commands ###
